# Generated by Django 5.2.11 on 2026-02-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('neet_status', models.CharField(max_length=50)),
                ('college_preference', models.CharField(choices=[('govt', 'Government'), ('private', 'Private'), ('abroad', 'Abroad')], max_length=20)),
                ('education_loan', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
