# Generated by Django 5.2.11 on 2026-02-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='neet_status',
            field=models.CharField(choices=[('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('waiting', 'Waiting for Result'), ('appearing', 'Appearing This Year')], max_length=20),
        ),
    ]
