# Generated by Django 5.2.11 on 2026-02-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0002_alter_registration_neet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobilenumber',
            field=models.CharField(max_length=10),
        ),
    ]
